[package]
name = "pyproc-browser-desktop"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_Security",
  "Win32_Security_Cryptography",
  "Win32_System_StationsAndDesktops",
  "Win32_System_Threading",
] }

[[bin]]
name = "pyproc-browser-desktop"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
